name: End-to-End Tests

on:
  push:
    branches:
      - main
      - develop  # You can add other branches as needed
  pull_request:
    branches:
      - main
      - develop

jobs:
  e2e:
    runs-on: ubuntu-latest

    services:
      xserver:
        image: cypress/browsers:node14.17.0-chrome93-ff92
        options: >-
          --shm-size 2g

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Match this with your local Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run E2E tests
        run: npx cypress run --headless
